### ISSUE TITLE
Day 1 - README.md 작성

### ISSUE THREAD

**Issue by WhiteCapella** [DE32megabox/airflow#2]
작성 가이드

# 제목
repository 소개

## 설치방법
```
설치방법을 담은 bash 코드
담아야 할 내용 
- repository 설치 코드 : git clone ~~~
- repository 설치 이후 환경설정 : pdm install ~~, source .venv/bin/activate 등등
- 개발환경에 관한 코드 : git branch ~~ 등등
```

## 실행예제
```
실행방법을 담은 bash 코드
```

```
코드를 실행하면 나오는 내용에 대한 코드
```

완성 후 해당 README.md 파일 위치를 댓글로 태그

**Comment by WhiteCapella** [comment]
https://github.com/DE32megabox/load/blob/dev/d1.0.0/README.md

**Comment by minju210** [comment]
https://github.com/DE32megabox/transform/blob/dev/d1.0.0/README.md

**Comment by Seokxkyu** [comment]
https://github.com/DE32megabox/extract/blob/dev/d1.0.0/README.md

**Comment by WhiteCapella** [comment]
mission complete
